### ISSUE TITLE
Update/ Finalize READme

### ISSUE THREAD

**Issue by MANSI288** [RyanGuzelian/Alpha_team_soen341project2023#10]
To do-
finalize readme for sprint 1 by adding roles and reviewing description

**Comment by MANSI288** [comment]
Readme is finalized by adding respective roles discussed

**Comment by golbr** [comment]
- Added a description, team members' real names along with their GitHub usernames. as well as everyone's strengths. 
- Included a brief description of the project approach and technology stack.
