### ISSUE TITLE
Create Sign In / Sign Up pages

### ISSUE THREAD

**Issue by RyanGuzelian** [RyanGuzelian/Alpha_team_soen341project2023#14]
Create form taking email and password.

Make both follow the same style, save values of form to variables that can be sent to the backend.

Save login values into the DB

**Comment by golbr** [comment]
**Related User Story:**
- #1

**Comment by MANSI288** [comment]
Sign In / Sign Up pages made by RG added to the frontend file: ref: pull req #56
